// ============================================================================
// register_dongle_v2_module_rom.c
// Generated S-expression module for register_dongle_v2 (M-port: const ROM tables)
// DO NOT EDIT - Generated by s_expr_dsl v5.3 C-emit
// ============================================================================

#include "s_engine_types.h"
#include "s_engine_module.h"
#include "s_engine_eval.h"
#include "s_engine_node.h"
#include "s_engine_exception.h"
#include "s_engine_event_queue.h"
#include "s_engine_stack.h"
#include "se_dict_string.h"
#include "se_dict_hash.h"
#include "s_engine_builtins_shared_helpers.h"
#include "s_engine_builtins_pred.h"
#include "s_engine_builtins_delays.h"
#include "s_engine_builtins_flow_control.h"
#include "s_engine_builtins_dispatch.h"
#include "s_engine_builtins_verify.h"
#include "s_engine_builtins_oneshot.h"
#include "s_engine_builtins_return_codes.h"
#include "s_engine_builtins_quads.h"
#include "s_engine_builtins_dict.h"
#include "s_engine_builtins_stack.h"
#include "s_engine_builtins_spawn.h"
#include "s_engine_rom.h"  // s_engine_rom_t (M-port)
#include "register_dongle_v2_records.h"
#include "register_dongle_v2.h"

// Forward declarations for USER functions only.
// Builtins are visible via the builtins_*.h includes above (static defs).
// Linker resolves user fns or errors at link time.
extern void send_register(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void handle_register_ack(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void handle_commission_set(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void handle_commission_clear(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void send_nak(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void send_manifest_reply(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void send_heartbeat(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void send_pong(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void handle_shell_exec(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern s_expr_result_t handle_internal_events(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern s_expr_result_t toggle_led(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);

static const s_expr_field_desc_t register_dongle_v2_dongle_record_fields[] = {
    { .name_hash = 0x57075F2EU, .offset = 0, .size = 4 }
};

static const s_expr_record_desc_t register_dongle_v2_records[] = {
    { .name_hash = 0x84FEA724U, .total_size = 4, .field_count = 1, .fields = register_dongle_v2_dongle_record_fields }
};

// Tree: register_dongle_v2 (params=212, nodes=62)
static const s_expr_param_t register_dongle_v2_register_dongle_v2_params[] = {
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 211, .parent_offset = 0 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 0, .func_index = 0 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 1 },
    { .type = 0x48, .index_to_pointer = 0, .node_index = 1, .func_index = 0 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 4 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 0x0U },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 5 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 6 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 2, .func_index = 1 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 8 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 197, .parent_offset = 9 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 3, .func_index = 2 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 4 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 0 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 58, .parent_offset = 3 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 4, .func_index = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 12, .parent_offset = 1 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 5, .func_index = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 6, .func_index = 1 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x89, .index_to_pointer = 0, .node_index = 7, .func_index = 5 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 0 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 7 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 8 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 8, .func_index = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 10 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 12, .parent_offset = 13 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 42, .parent_offset = 14 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 9, .func_index = 7 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 259 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 8, .parent_offset = 2 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 10, .func_index = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 11, .func_index = 2 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 4 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 12, .func_index = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 8, .parent_offset = 10 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 261 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 8, .parent_offset = 12 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 13, .func_index = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 14, .func_index = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 4 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 15, .func_index = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 8, .parent_offset = 20 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 262 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 8, .parent_offset = 22 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 16, .func_index = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 17, .func_index = 4 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 4 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 18, .func_index = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 8, .parent_offset = 30 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = -1 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 8, .parent_offset = 32 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 19, .func_index = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 20, .func_index = 5 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 4 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 21, .func_index = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 8, .parent_offset = 40 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 42, .parent_offset = 56 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 58, .parent_offset = 61 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 1 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 48, .parent_offset = 63 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 22, .func_index = 7 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 263 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 8, .parent_offset = 2 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 23, .func_index = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 24, .func_index = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 4 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 25, .func_index = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 8, .parent_offset = 10 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 264 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 14, .parent_offset = 12 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 26, .func_index = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 27, .func_index = 7 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 0, .str_len = 53 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 5 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 28, .func_index = 0 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 4 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 0x2U },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 9 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 10 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 29, .func_index = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 12 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 14, .parent_offset = 26 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 262 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 8, .parent_offset = 28 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 30, .func_index = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 31, .func_index = 4 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 4 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 32, .func_index = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 8, .parent_offset = 36 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = -1 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 8, .parent_offset = 38 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 33, .func_index = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 34, .func_index = 5 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 4 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 35, .func_index = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 8, .parent_offset = 46 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 48, .parent_offset = 111 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 71, .parent_offset = 113 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 36, .func_index = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 12, .parent_offset = 1 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 37, .func_index = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 38, .func_index = 8 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 3 },
    { .type = 0x07, .index_to_pointer = 1, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x89, .index_to_pointer = 1, .node_index = 39, .func_index = 5 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 7 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 8 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 40, .func_index = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 10 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 12, .parent_offset = 13 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 14 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 41, .func_index = 8 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 16 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 52, .parent_offset = 17 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 42, .func_index = 7 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 260 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 8, .parent_offset = 2 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 43, .func_index = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 44, .func_index = 9 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 4 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 45, .func_index = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 8, .parent_offset = 10 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 263 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 8, .parent_offset = 12 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 46, .func_index = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 47, .func_index = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 4 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 48, .func_index = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 8, .parent_offset = 20 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 262 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 8, .parent_offset = 22 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 49, .func_index = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 50, .func_index = 4 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 4 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 51, .func_index = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 8, .parent_offset = 30 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 265 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 8, .parent_offset = 32 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 52, .func_index = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 53, .func_index = 10 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 4 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 54, .func_index = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 8, .parent_offset = 40 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = -1 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 8, .parent_offset = 42 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 55, .func_index = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 56, .func_index = 5 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 4 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 57, .func_index = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 8, .parent_offset = 50 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 52, .parent_offset = 69 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 71, .parent_offset = 184 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = -1 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 9, .parent_offset = 186 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 58, .func_index = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 59, .func_index = 7 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 1, .str_len = 27 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 5 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 60, .func_index = 9 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 7 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 9, .parent_offset = 195 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 197, .parent_offset = 206 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 207 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 61, .func_index = 10 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 209 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 211, .parent_offset = 0 }
};

// Tree definitions
static const s_expr_tree_def_t register_dongle_v2_trees[] = {
    {
        .name_hash = 0xAE14A061U,
        .record_hash = 0x84FEA724U,
        .params = register_dongle_v2_register_dongle_v2_params,
        .param_count = 212,
        .func_node_count = 62,
        .pointer_count = 2,
        .defaults_index = 65535,
    }
};

static const s_expr_oneshot_fn_t register_dongle_v2_oneshot_fns[] = {
    se_set_field,  // 0: SE_SET_FIELD
    send_register,  // 1: send_register
    handle_register_ack,  // 2: handle_register_ack
    handle_commission_set,  // 3: handle_commission_set
    handle_commission_clear,  // 4: handle_commission_clear
    send_nak,  // 5: send_nak
    send_manifest_reply,  // 6: send_manifest_reply
    se_log,  // 7: SE_LOG
    send_heartbeat,  // 8: send_heartbeat
    send_pong,  // 9: send_pong
    handle_shell_exec  // 10: handle_shell_exec
};

static const s_expr_main_fn_t register_dongle_v2_main_fns[] = {
    se_function_interface,  // 0: SE_FUNCTION_INTERFACE
    handle_internal_events,  // 1: handle_internal_events
    se_state_machine,  // 2: SE_STATE_MACHINE
    se_fork,  // 3: SE_FORK
    se_chain_flow,  // 4: SE_CHAIN_FLOW
    se_tick_delay,  // 5: SE_TICK_DELAY
    se_return_pipeline_reset,  // 6: SE_RETURN_PIPELINE_RESET
    se_event_dispatch,  // 7: SE_EVENT_DISPATCH
    toggle_led,  // 8: toggle_led
    se_return_terminate,  // 9: SE_RETURN_TERMINATE
    se_return_halt  // 10: SE_RETURN_HALT
};

static const s_expr_pred_fn_t register_dongle_v2_pred_fns[1] = { NULL };

// Top-level ROM handle (M-port)
const s_engine_rom_t register_dongle_v2_module_rom = {
    .name_hash = 0xAE14A061U,
    .is_64bit = false,
    .trees = register_dongle_v2_trees,
    .tree_count = 1,
    .records = register_dongle_v2_records,
    .record_count = 1,
    .string_table = register_dongle_v2_strings,
    .string_count = 2,
    .constants = NULL,
    .const_count = 0,
    .oneshot_fns = register_dongle_v2_oneshot_fns,
    .oneshot_count = 11,
    .main_fns = register_dongle_v2_main_fns,
    .main_count = 11,
    .pred_fns = register_dongle_v2_pred_fns,
    .pred_count = 0,
    .max_func_node_count = 62,
    .max_pointer_count = 2,
    .max_param_count = 212,
    .bump_buffer_size = 0,  // TODO: DSL-computed when bump allocator lands
};

