// ============================================================================
// register_dongle_v2_records.h
// Generated record structures for register_dongle_v2
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// ============================================================================

#ifndef REGISTER_DONGLE_V2_RECORDS_H
#define REGISTER_DONGLE_V2_RECORDS_H

#include <stdint.h>
#include <stdbool.h>

// Forward declarations
typedef struct dongle_record_s dongle_record_t;

// Record: dongle_record (size=4, align=4)
struct dongle_record_s {
    int32_t dongle_state;  // offset=0, size=4
};

#endif // REGISTER_DONGLE_V2_RECORDS_H
