/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#include "chaintree_handle_kb_info.h"

const chaintree_kb_info_t ct_k6oenybg_kb_table[4] = {
    {
        .kb_name = "kb0",
        .root_node_index = 0,
        .start_index = 0,
        .node_count = 9,
        .max_depth = 2,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "kb1",
        .root_node_index = 9,
        .start_index = 9,
        .node_count = 5,
        .max_depth = 2,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "kb1_functions",
        .root_node_index = 14,
        .start_index = 14,
        .node_count = 1,
        .max_depth = 0,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "kb0_functions",
        .root_node_index = 20,
        .start_index = 20,
        .node_count = 1,
        .max_depth = 0,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
};
