/* Auto-generated by ChainTree Pipeline (LuaJIT) - Blackboard */
#include "chaintree_handle_blackboard.h"

cfl_bb_field_t ct_kae52wtn_bb_fields[] = {
    { .name_hash = 0, .offset = 0, .size = 4 },  /* adc0_mean */
    { .name_hash = 0, .offset = 4, .size = 4 },  /* adc0_max */
    { .name_hash = 0, .offset = 8, .size = 4 },  /* adc0_rms */
    { .name_hash = 0, .offset = 12, .size = 4 },  /* adc1_mean */
    { .name_hash = 0, .offset = 16, .size = 4 },  /* adc1_max */
    { .name_hash = 0, .offset = 20, .size = 4 },  /* adc1_rms */
    { .name_hash = 0, .offset = 24, .size = 4 },  /* adc2_mean */
    { .name_hash = 0, .offset = 28, .size = 4 },  /* adc2_max */
    { .name_hash = 0, .offset = 32, .size = 4 },  /* adc2_rms */
};

static uint8_t ct_kae52wtn_bb_defaults[36] __attribute__((aligned(8))) = {0};

static void ct_kae52wtn_bb_init_defaults(void) {
}

cfl_bb_record_t ct_kae52wtn_bb_record = {
    .name_hash = 0,
    .total_size = 36,
    .field_count = 9,
    .fields = ct_kae52wtn_bb_fields,
    .defaults = ct_kae52wtn_bb_defaults,
};

cfl_bb_table_t ct_kae52wtn_bb_table = {
    .blackboard = &ct_kae52wtn_bb_record,
    .const_records = NULL,
    .const_record_count = 0,
};

void ct_kae52wtn_bb_init_hashes(void) {
    ct_kae52wtn_bb_fields[0].name_hash = cfl_bb_hash("adc0_mean");
    ct_kae52wtn_bb_fields[1].name_hash = cfl_bb_hash("adc0_max");
    ct_kae52wtn_bb_fields[2].name_hash = cfl_bb_hash("adc0_rms");
    ct_kae52wtn_bb_fields[3].name_hash = cfl_bb_hash("adc1_mean");
    ct_kae52wtn_bb_fields[4].name_hash = cfl_bb_hash("adc1_max");
    ct_kae52wtn_bb_fields[5].name_hash = cfl_bb_hash("adc1_rms");
    ct_kae52wtn_bb_fields[6].name_hash = cfl_bb_hash("adc2_mean");
    ct_kae52wtn_bb_fields[7].name_hash = cfl_bb_hash("adc2_max");
    ct_kae52wtn_bb_fields[8].name_hash = cfl_bb_hash("adc2_rms");
    ct_kae52wtn_bb_record.name_hash = cfl_bb_hash("adc_streams");
    ct_kae52wtn_bb_init_defaults();
}
