/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#ifndef CHAINTREE_HANDLE_H
#define CHAINTREE_HANDLE_H

#include "chaintree_support.h"
#include "chaintree_handle_nodes.h"
#include "chaintree_handle_links.h"
#include "chaintree_handle_events.h"
#include "chaintree_handle_bitmasks.h"
#include "chaintree_handle_kb_info.h"
#include "chaintree_handle_node_data.h"
#include "chaintree_handle_functions.h"

extern const chaintree_handle_t g_chaintree_handle;

#endif /* CHAINTREE_HANDLE_H */