/* Auto-generated by ChainTree Pipeline (LuaJIT) - Blackboard */
#ifndef CHAINTREE_HANDLE_BLACKBOARD_H
#define CHAINTREE_HANDLE_BLACKBOARD_H

#include "cfl_blackboard.h"

/* ===== Blackboard: adc_streams ===== */

#define BB_ADC_STREAMS_SIZE 36

#define BB_ADC0_MEAN_OFFSET                      0
#define BB_ADC0_MAX_OFFSET                       4
#define BB_ADC0_RMS_OFFSET                       8
#define BB_ADC1_MEAN_OFFSET                      12
#define BB_ADC1_MAX_OFFSET                       16
#define BB_ADC1_RMS_OFFSET                       20
#define BB_ADC2_MEAN_OFFSET                      24
#define BB_ADC2_MAX_OFFSET                       28
#define BB_ADC2_RMS_OFFSET                       32

extern cfl_bb_field_t ct_m6s5rj6o_bb_fields[];
extern cfl_bb_record_t ct_m6s5rj6o_bb_record;

extern cfl_bb_table_t ct_m6s5rj6o_bb_table;
void ct_m6s5rj6o_bb_init_hashes(void);

/* ===== Stable aliases (use these from application code) ===== */
#define chaintree_handle_bb_table       ct_m6s5rj6o_bb_table
#define chaintree_handle_bb_init_hashes ct_m6s5rj6o_bb_init_hashes

#endif /* CHAINTREE_HANDLE_BLACKBOARD_H */