/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#ifndef CHAINTREE_HANDLE_KB_INFO_H
#define CHAINTREE_HANDLE_KB_INFO_H

#include "chaintree_support.h"

#define CT_OFFKYU7F_KB_COUNT 6


extern const chaintree_kb_info_t ct_offkyu7f_kb_table[6];

#endif /* CHAINTREE_HANDLE_KB_INFO_H */