/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#ifndef CHAINTREE_HANDLE_LINKS_H
#define CHAINTREE_HANDLE_LINKS_H

#include <stdint.h>

#define CT_KAE52WTN_LINK_TABLE_SIZE 16

extern const uint16_t ct_kae52wtn_link_table[CT_KAE52WTN_LINK_TABLE_SIZE];

#endif /* CHAINTREE_HANDLE_LINKS_H */