/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#include "chaintree_handle_nodes.h"

/* Node array - preserves original indices; filtered nodes leave gaps */
const chaintree_node_t ct_oeogzsbm_nodes[17] = {
    /* [0] _0 */
    {
        .node_index = 0,
        .parent_index = 65535,
        .depth = 0,
        .link_start = 0,
        .link_count = 0x0001,  /* count=1, auto_start=false */
        .main_function_index = 3,
        .init_function_index = 3,
        .aux_function_index = 2,
        .term_function_index = 4,
        .node_data_id = 2
    },
    /* [1] _0 [AUTO_START] */
    {
        .node_index = 1,
        .parent_index = 0,
        .depth = 1,
        .link_start = 1,
        .link_count = 0x8004,  /* count=4, auto_start=true */
        .main_function_index = 1,
        .init_function_index = 1,
        .aux_function_index = 1,
        .term_function_index = 2,
        .node_data_id = 65535
    },
    /* [2] _0 */
    {
        .node_index = 2,
        .parent_index = 1,
        .depth = 2,
        .link_start = 5,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 2,
        .init_function_index = 5,
        .aux_function_index = 0,
        .term_function_index = 0,
        .node_data_id = 3
    },
    /* [3] _1 */
    {
        .node_index = 3,
        .parent_index = 1,
        .depth = 2,
        .link_start = 0,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 5,
        .init_function_index = 6,
        .aux_function_index = 3,
        .term_function_index = 7,
        .node_data_id = 0
    },
    /* [4] _2 */
    {
        .node_index = 4,
        .parent_index = 1,
        .depth = 2,
        .link_start = 0,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 2,
        .init_function_index = 8,
        .aux_function_index = 0,
        .term_function_index = 0,
        .node_data_id = 65535
    },
    /* [5] _3 */
    {
        .node_index = 5,
        .parent_index = 1,
        .depth = 2,
        .link_start = 0,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 4,
        .init_function_index = 0,
        .aux_function_index = 0,
        .term_function_index = 0,
        .node_data_id = 65535
    },
    /* [6] kb0 */
    {
        .node_index = 6,
        .parent_index = 65535,
        .depth = 0,
        .link_start = 0,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 0,
        .init_function_index = 0,
        .aux_function_index = 0,
        .term_function_index = 0,
        .node_data_id = 65535
    },
    /* [7] FILTERED */ {
        .node_index = 7, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [8] FILTERED */ {
        .node_index = 8, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [9] FILTERED */ {
        .node_index = 9, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [10] FILTERED */ {
        .node_index = 10, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [11] FILTERED */ {
        .node_index = 11, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [12] FILTERED */ {
        .node_index = 12, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [13] FILTERED */ {
        .node_index = 13, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [14] FILTERED */ {
        .node_index = 14, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [15] FILTERED */ {
        .node_index = 15, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [16] event_string_table */
    {
        .node_index = 16,
        .parent_index = 65535,
        .depth = 0,
        .link_start = 0,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 0,
        .init_function_index = 0,
        .aux_function_index = 0,
        .term_function_index = 0,
        .node_data_id = 1
    },
};
