/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#ifndef CHAINTREE_HANDLE_NODES_H
#define CHAINTREE_HANDLE_NODES_H

#include "chaintree_support.h"

#define CT_VY7EJ4JA_NODE_COUNT 46

extern const chaintree_node_t ct_vy7ej4ja_nodes[CT_VY7EJ4JA_NODE_COUNT];

#endif /* CHAINTREE_HANDLE_NODES_H */