/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#ifndef CHAINTREE_HANDLE_NODES_H
#define CHAINTREE_HANDLE_NODES_H

#include "chaintree_support.h"

#define CT_8FWLHYXG_NODE_COUNT 50

extern const chaintree_node_t ct_8fwlhyxg_nodes[CT_8FWLHYXG_NODE_COUNT];

#endif /* CHAINTREE_HANDLE_NODES_H */