/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#ifndef CHAINTREE_HANDLE_LINKS_H
#define CHAINTREE_HANDLE_LINKS_H

#include <stdint.h>

#define CT_8FWLHYXG_LINK_TABLE_SIZE 24

extern const uint16_t ct_8fwlhyxg_link_table[CT_8FWLHYXG_LINK_TABLE_SIZE];

#endif /* CHAINTREE_HANDLE_LINKS_H */