/* Auto-generated by ChainTree Pipeline (LuaJIT) */

#include "chaintree_handle.h"

const chaintree_handle_t g_chaintree_handle = {
    .unique_id = "ct_oeogzsbm",

    .nodes = ct_oeogzsbm_nodes,
    .node_count = 8,

    .main_functions = ct_oeogzsbm_main_functions,
    .main_function_count = 6,
    .one_shot_functions = ct_oeogzsbm_one_shot_functions,
    .one_shot_function_count = 10,
    .boolean_functions = ct_oeogzsbm_boolean_functions,
    .boolean_function_count = 4,

    .main_function_names = ct_oeogzsbm_main_function_names,
    .one_shot_function_names = ct_oeogzsbm_one_shot_function_names,
    .boolean_function_names = ct_oeogzsbm_boolean_function_names,

    .main_function_usage_count = ct_oeogzsbm_main_function_usage_count,

    .link_table = ct_oeogzsbm_link_table,
    .link_table_size = 5,

    .event_strings = (const char **)ct_oeogzsbm_event_strings,
    .event_count = 21,

    .bitmask_names = (const char **)ct_oeogzsbm_bitmask_names,
    .bitmask_count = 0,

    .kb_table = ct_oeogzsbm_kb_table,
    .kb_count = 2,

    .node_data_records = ct_oeogzsbm_node_data_records,
    .node_data_records_count = 76,
    .node_data_strings = ct_oeogzsbm_node_data_strings,
    .node_data_strings_size = 608,
    .node_data_controls = ct_oeogzsbm_node_data_controls,
    .node_data_controls_count = 4,
    .bb_table = NULL
};
