/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#ifndef CHAINTREE_HANDLE_NODE_DATA_H
#define CHAINTREE_HANDLE_NODE_DATA_H

#include "chaintree_support.h"

extern const json_record_t ct_8fwlhyxg_node_data_records[196];
extern const char ct_8fwlhyxg_node_data_strings[651];
extern const record_control_t ct_8fwlhyxg_node_data_controls[10];

#endif /* CHAINTREE_HANDLE_NODE_DATA_H */
