/* Auto-generated by ChainTree Pipeline (LuaJIT) */

#include "chaintree_handle.h"
#include "chaintree_handle_blackboard.h"

const chaintree_handle_t g_chaintree_handle = {
    .unique_id = "ct_8fwlhyxg",

    .nodes = ct_8fwlhyxg_nodes,
    .node_count = 31,

    .main_functions = ct_8fwlhyxg_main_functions,
    .main_function_count = 6,
    .one_shot_functions = ct_8fwlhyxg_one_shot_functions,
    .one_shot_function_count = 14,
    .boolean_functions = ct_8fwlhyxg_boolean_functions,
    .boolean_function_count = 4,

    .main_function_names = ct_8fwlhyxg_main_function_names,
    .one_shot_function_names = ct_8fwlhyxg_one_shot_function_names,
    .boolean_function_names = ct_8fwlhyxg_boolean_function_names,

    .main_function_usage_count = ct_8fwlhyxg_main_function_usage_count,

    .link_table = ct_8fwlhyxg_link_table,
    .link_table_size = 24,

    .event_strings = (const char **)ct_8fwlhyxg_event_strings,
    .event_count = 26,

    .bitmask_names = (const char **)ct_8fwlhyxg_bitmask_names,
    .bitmask_count = 0,

    .kb_table = ct_8fwlhyxg_kb_table,
    .kb_count = 6,

    .node_data_records = ct_8fwlhyxg_node_data_records,
    .node_data_records_count = 196,
    .node_data_strings = ct_8fwlhyxg_node_data_strings,
    .node_data_strings_size = 651,
    .node_data_controls = ct_8fwlhyxg_node_data_controls,
    .node_data_controls_count = 10,
    .bb_table = &ct_8fwlhyxg_bb_table
};
