/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#ifndef CHAINTREE_HANDLE_FUNCTIONS_H
#define CHAINTREE_HANDLE_FUNCTIONS_H

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "chaintree_support.h"

/* Main function enum */
typedef enum {
    MAIN_FUNC_CFL_NULL = 0,
    MAIN_FUNC_CFL_COLUMN_MAIN = 1,
    MAIN_FUNC_CFL_DISABLE = 2,
    MAIN_FUNC_CFL_GATE_NODE_MAIN = 3,
    MAIN_FUNC_CFL_RESET = 4,
    MAIN_FUNC_CFL_WAIT = 5,
    MAIN_FUNC_COUNT = 6
} MAIN_FUNC_t;

/* One-shot function enum */
typedef enum {
    ONE_SHOT_FUNC_CFL_NULL = 0,
    ONE_SHOT_FUNC_ADC_READ = 1,
    ONE_SHOT_FUNC_APP_ECHO = 2,
    ONE_SHOT_FUNC_CFL_COLUMN_INIT = 3,
    ONE_SHOT_FUNC_CFL_COLUMN_TERM = 4,
    ONE_SHOT_FUNC_CFL_GATE_NODE_INIT = 5,
    ONE_SHOT_FUNC_CFL_GATE_NODE_TERM = 6,
    ONE_SHOT_FUNC_CFL_WAIT_INIT = 7,
    ONE_SHOT_FUNC_CFL_WAIT_TERM = 8,
    ONE_SHOT_FUNC_MON_PING_REPLY = 9,
    ONE_SHOT_FUNC_MON_SNAPSHOT = 10,
    ONE_SHOT_FUNC_MON_CMD_TIMEOUT = 11,
    ONE_SHOT_FUNC_COUNT = 12
} ONE_SHOT_FUNC_t;

/* Boolean function enum */
typedef enum {
    BOOL_FUNC_CFL_NULL = 0,
    BOOL_FUNC_CFL_COLUMN_NULL = 1,
    BOOL_FUNC_CFL_GATE_NODE_NULL = 2,
    BOOL_FUNC_CFL_WAIT_FOR_EVENT = 3,
    BOOL_FUNC_COUNT = 4
} BOOL_FUNC_t;

extern const main_function_t ct_kae52wtn_main_functions[6];
extern const one_shot_function_t ct_kae52wtn_one_shot_functions[12];
extern const boolean_function_t ct_kae52wtn_boolean_functions[4];

extern const uint16_t ct_kae52wtn_main_function_usage_count[6];

extern const char *ct_kae52wtn_main_function_names[6];
extern const char *ct_kae52wtn_one_shot_function_names[12];
extern const char *ct_kae52wtn_boolean_function_names[4];

#endif /* CHAINTREE_HANDLE_FUNCTIONS_H */