/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#include "chaintree_handle_links.h"

const uint16_t ct_j5te5xxi_link_table[28] = {
    28, 29, 30, 1, 5, 2, 3, 4, 6, 7,
    8, 10, 11, 12, 13, 15, 19, 23, 27, 16,
    17, 18, 20, 21, 22, 24, 25, 26
};
