/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#include "chaintree_handle_links.h"

const uint16_t ct_kae52wtn_link_table[16] = {
    10, 11, 12, 13, 15, 16, 17, 18, 1, 5,
    2, 3, 4, 6, 7, 8
};
