/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#include "chaintree_handle_links.h"

const uint16_t ct_8fwlhyxg_link_table[24] = {
    10, 11, 12, 13, 6, 7, 8, 2, 3, 4,
    1, 5, 15, 19, 23, 16, 17, 18, 20, 21,
    22, 24, 25, 26
};
