/* Auto-generated by ChainTree Pipeline (LuaJIT) - Generic Runtime */
#ifndef CHAINTREE_SUPPORT_H
#define CHAINTREE_SUPPORT_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* ===== Function Pointer Types ===== */
typedef unsigned (*main_function_t)(void *handle, unsigned bool_function_index,
    unsigned node_index, unsigned event_type, unsigned event_id, void *event_data);
typedef void (*one_shot_function_t)(void *handle, unsigned node_index);
typedef bool (*boolean_function_t)(void *handle, unsigned node_index,
    unsigned event_type, unsigned event_id, void *event_data);

/* ===== Node Structure ===== */
typedef struct {
    uint16_t node_index;
    uint16_t parent_index;
    uint16_t depth;
    uint16_t link_start;
    uint16_t link_count;          /* Bits 0-14: count, Bit 15: auto_start flag */
    uint16_t main_function_index;
    uint16_t init_function_index;
    uint16_t aux_function_index;
    uint16_t term_function_index;
    uint16_t node_data_id;
} chaintree_node_t;

/* ===== Link Count Bit Packing Macros ===== */
#define LINK_COUNT_MASK     0x7FFF
#define AUTO_START_BIT      0x8000

#define GET_LINK_COUNT(node)     ((node)->link_count & LINK_COUNT_MASK)
#define GET_AUTO_START(node)     (((node)->link_count & AUTO_START_BIT) != 0)
#define PACK_LINK_COUNT(count, auto_start) \
    (((count) & LINK_COUNT_MASK) | ((auto_start) ? AUTO_START_BIT : 0))

/* ===== Node Alias Structure ===== */
typedef struct {
    const char *alias;
    uint16_t node_index;
} node_alias_t;

/* ===== Knowledge Base Info ===== */
typedef struct {
    const char *kb_name;
    uint16_t root_node_index;
    uint16_t start_index;
    uint16_t node_count;
    uint16_t max_depth;
    uint16_t memory_factor;
    const node_alias_t *aliases;
    uint16_t alias_count;
} chaintree_kb_info_t;

/* ===== Node Data Structures ===== */
typedef enum {
    JSON_TYPE_STRING = 0,
    JSON_TYPE_INT32 = 1,
    JSON_TYPE_FLOAT32 = 2,
    JSON_TYPE_NULL = 3,
    JSON_TYPE_BOOL = 4,
    JSON_TYPE_ARRAY = 5,
    JSON_TYPE_OBJECT = 6
} json_type_t;

typedef struct {
    json_type_t object_type;
    union {
        uint32_t string_offset;
        int32_t i32_value;
        float f32_value;
        uint8_t bool_value;
        uint32_t container_count;
    } value;
} json_record_t;

typedef struct {
    uint32_t start_position;
    uint32_t num_records;
} record_control_t;

/* ===== Forward declaration for blackboard types ===== */
struct cfl_bb_table;
typedef struct cfl_bb_table cfl_bb_table_t;

/* ===== Handle Structure ===== */
typedef struct {
    const char *unique_id;
    const chaintree_node_t *nodes;
    uint16_t node_count;
    const main_function_t *main_functions;
    uint16_t main_function_count;
    const one_shot_function_t *one_shot_functions;
    uint16_t one_shot_function_count;
    const boolean_function_t *boolean_functions;
    uint16_t boolean_function_count;
    const char **main_function_names;
    const char **one_shot_function_names;
    const char **boolean_function_names;
    const uint16_t *main_function_usage_count;
    const uint16_t *link_table;
    uint16_t link_table_size;
    const char **event_strings;
    uint16_t event_count;
    const char **bitmask_names;
    uint16_t bitmask_count;
    const chaintree_kb_info_t *kb_table;
    uint16_t kb_count;
    const json_record_t *node_data_records;
    uint16_t node_data_records_count;
    const char *node_data_strings;
    uint16_t node_data_strings_size;
    const record_control_t *node_data_controls;
    uint16_t node_data_controls_count;
    /* ---- Blackboard and constant records (NULL if not defined) ---- */
    const cfl_bb_table_t *bb_table;
} chaintree_handle_t;

/* ===== Generic Lookup Functions ===== */
const char* ct_get_main_function_name(const chaintree_handle_t *handle, uint16_t func_index);
int ct_get_main_function_index(const chaintree_handle_t *handle, const char *func_name);
const char* ct_get_one_shot_function_name(const chaintree_handle_t *handle, uint16_t func_index);
int ct_get_one_shot_function_index(const chaintree_handle_t *handle, const char *func_name);
const char* ct_get_boolean_function_name(const chaintree_handle_t *handle, uint16_t func_index);
int ct_get_boolean_function_index(const chaintree_handle_t *handle, const char *func_name);
const char* ct_get_event_name(const chaintree_handle_t *handle, uint16_t event_index);
int ct_get_event_index(const chaintree_handle_t *handle, const char *name);
const char* ct_get_bitmask_name(const chaintree_handle_t *handle, uint8_t bit_index);
int ct_get_bitmask_index(const chaintree_handle_t *handle, const char *name);
uint16_t ct_get_kb_count(const chaintree_handle_t *handle);

#endif /* CHAINTREE_SUPPORT_H */