/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#include "chaintree_handle_nodes.h"

/* Node array - preserves original indices; filtered nodes leave gaps */
const chaintree_node_t ct_j5te5xxi_nodes[54] = {
    /* [0] _0 */
    {
        .node_index = 0,
        .parent_index = 65535,
        .depth = 0,
        .link_start = 3,
        .link_count = 0x0002,  /* count=2, auto_start=false */
        .main_function_index = 3,
        .init_function_index = 8,
        .aux_function_index = 2,
        .term_function_index = 9,
        .node_data_id = 2
    },
    /* [1] _0 [AUTO_START] */
    {
        .node_index = 1,
        .parent_index = 0,
        .depth = 1,
        .link_start = 5,
        .link_count = 0x8003,  /* count=3, auto_start=true */
        .main_function_index = 1,
        .init_function_index = 6,
        .aux_function_index = 1,
        .term_function_index = 7,
        .node_data_id = 65535
    },
    /* [2] _0 */
    {
        .node_index = 2,
        .parent_index = 1,
        .depth = 2,
        .link_start = 8,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 5,
        .init_function_index = 10,
        .aux_function_index = 3,
        .term_function_index = 11,
        .node_data_id = 3
    },
    /* [3] _1 */
    {
        .node_index = 3,
        .parent_index = 1,
        .depth = 2,
        .link_start = 8,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 2,
        .init_function_index = 12,
        .aux_function_index = 0,
        .term_function_index = 0,
        .node_data_id = 65535
    },
    /* [4] _2 */
    {
        .node_index = 4,
        .parent_index = 1,
        .depth = 2,
        .link_start = 8,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 4,
        .init_function_index = 0,
        .aux_function_index = 0,
        .term_function_index = 0,
        .node_data_id = 65535
    },
    /* [5] _1 [AUTO_START] */
    {
        .node_index = 5,
        .parent_index = 0,
        .depth = 1,
        .link_start = 8,
        .link_count = 0x8003,  /* count=3, auto_start=true */
        .main_function_index = 1,
        .init_function_index = 6,
        .aux_function_index = 1,
        .term_function_index = 7,
        .node_data_id = 65535
    },
    /* [6] _0 */
    {
        .node_index = 6,
        .parent_index = 5,
        .depth = 2,
        .link_start = 11,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 5,
        .init_function_index = 10,
        .aux_function_index = 3,
        .term_function_index = 11,
        .node_data_id = 4
    },
    /* [7] _1 */
    {
        .node_index = 7,
        .parent_index = 5,
        .depth = 2,
        .link_start = 11,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 2,
        .init_function_index = 13,
        .aux_function_index = 0,
        .term_function_index = 0,
        .node_data_id = 65535
    },
    /* [8] _2 */
    {
        .node_index = 8,
        .parent_index = 5,
        .depth = 2,
        .link_start = 11,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 4,
        .init_function_index = 0,
        .aux_function_index = 0,
        .term_function_index = 0,
        .node_data_id = 65535
    },
    /* [9] _0 */
    {
        .node_index = 9,
        .parent_index = 65535,
        .depth = 0,
        .link_start = 11,
        .link_count = 0x0001,  /* count=1, auto_start=false */
        .main_function_index = 3,
        .init_function_index = 8,
        .aux_function_index = 2,
        .term_function_index = 9,
        .node_data_id = 5
    },
    /* [10] _0 [AUTO_START] */
    {
        .node_index = 10,
        .parent_index = 9,
        .depth = 1,
        .link_start = 12,
        .link_count = 0x8003,  /* count=3, auto_start=true */
        .main_function_index = 1,
        .init_function_index = 6,
        .aux_function_index = 1,
        .term_function_index = 7,
        .node_data_id = 65535
    },
    /* [11] _0 */
    {
        .node_index = 11,
        .parent_index = 10,
        .depth = 2,
        .link_start = 15,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 5,
        .init_function_index = 10,
        .aux_function_index = 3,
        .term_function_index = 11,
        .node_data_id = 6
    },
    /* [12] _1 */
    {
        .node_index = 12,
        .parent_index = 10,
        .depth = 2,
        .link_start = 15,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 2,
        .init_function_index = 1,
        .aux_function_index = 0,
        .term_function_index = 0,
        .node_data_id = 65535
    },
    /* [13] _2 */
    {
        .node_index = 13,
        .parent_index = 10,
        .depth = 2,
        .link_start = 15,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 4,
        .init_function_index = 0,
        .aux_function_index = 0,
        .term_function_index = 0,
        .node_data_id = 65535
    },
    /* [14] _0 */
    {
        .node_index = 14,
        .parent_index = 65535,
        .depth = 0,
        .link_start = 15,
        .link_count = 0x0004,  /* count=4, auto_start=false */
        .main_function_index = 3,
        .init_function_index = 8,
        .aux_function_index = 2,
        .term_function_index = 9,
        .node_data_id = 7
    },
    /* [15] _0 [AUTO_START] */
    {
        .node_index = 15,
        .parent_index = 14,
        .depth = 1,
        .link_start = 19,
        .link_count = 0x8003,  /* count=3, auto_start=true */
        .main_function_index = 1,
        .init_function_index = 6,
        .aux_function_index = 1,
        .term_function_index = 7,
        .node_data_id = 65535
    },
    /* [16] _0 */
    {
        .node_index = 16,
        .parent_index = 15,
        .depth = 2,
        .link_start = 22,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 5,
        .init_function_index = 10,
        .aux_function_index = 3,
        .term_function_index = 11,
        .node_data_id = 8
    },
    /* [17] _1 */
    {
        .node_index = 17,
        .parent_index = 15,
        .depth = 2,
        .link_start = 22,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 2,
        .init_function_index = 2,
        .aux_function_index = 0,
        .term_function_index = 0,
        .node_data_id = 65535
    },
    /* [18] _2 */
    {
        .node_index = 18,
        .parent_index = 15,
        .depth = 2,
        .link_start = 22,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 4,
        .init_function_index = 0,
        .aux_function_index = 0,
        .term_function_index = 0,
        .node_data_id = 65535
    },
    /* [19] _1 [AUTO_START] */
    {
        .node_index = 19,
        .parent_index = 14,
        .depth = 1,
        .link_start = 22,
        .link_count = 0x8003,  /* count=3, auto_start=true */
        .main_function_index = 1,
        .init_function_index = 6,
        .aux_function_index = 1,
        .term_function_index = 7,
        .node_data_id = 65535
    },
    /* [20] _0 */
    {
        .node_index = 20,
        .parent_index = 19,
        .depth = 2,
        .link_start = 25,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 5,
        .init_function_index = 10,
        .aux_function_index = 3,
        .term_function_index = 11,
        .node_data_id = 9
    },
    /* [21] _1 */
    {
        .node_index = 21,
        .parent_index = 19,
        .depth = 2,
        .link_start = 25,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 2,
        .init_function_index = 3,
        .aux_function_index = 0,
        .term_function_index = 0,
        .node_data_id = 65535
    },
    /* [22] _2 */
    {
        .node_index = 22,
        .parent_index = 19,
        .depth = 2,
        .link_start = 25,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 4,
        .init_function_index = 0,
        .aux_function_index = 0,
        .term_function_index = 0,
        .node_data_id = 65535
    },
    /* [23] _2 [AUTO_START] */
    {
        .node_index = 23,
        .parent_index = 14,
        .depth = 1,
        .link_start = 25,
        .link_count = 0x8003,  /* count=3, auto_start=true */
        .main_function_index = 1,
        .init_function_index = 6,
        .aux_function_index = 1,
        .term_function_index = 7,
        .node_data_id = 65535
    },
    /* [24] _0 */
    {
        .node_index = 24,
        .parent_index = 23,
        .depth = 2,
        .link_start = 28,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 5,
        .init_function_index = 10,
        .aux_function_index = 3,
        .term_function_index = 11,
        .node_data_id = 10
    },
    /* [25] _1 */
    {
        .node_index = 25,
        .parent_index = 23,
        .depth = 2,
        .link_start = 28,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 2,
        .init_function_index = 4,
        .aux_function_index = 0,
        .term_function_index = 0,
        .node_data_id = 65535
    },
    /* [26] _2 */
    {
        .node_index = 26,
        .parent_index = 23,
        .depth = 2,
        .link_start = 28,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 4,
        .init_function_index = 0,
        .aux_function_index = 0,
        .term_function_index = 0,
        .node_data_id = 65535
    },
    /* [27] _3 [AUTO_START] */
    {
        .node_index = 27,
        .parent_index = 14,
        .depth = 1,
        .link_start = 0,
        .link_count = 0x8003,  /* count=3, auto_start=true */
        .main_function_index = 1,
        .init_function_index = 6,
        .aux_function_index = 1,
        .term_function_index = 7,
        .node_data_id = 65535
    },
    /* [28] _0 */
    {
        .node_index = 28,
        .parent_index = 27,
        .depth = 2,
        .link_start = 3,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 5,
        .init_function_index = 10,
        .aux_function_index = 3,
        .term_function_index = 11,
        .node_data_id = 0
    },
    /* [29] _1 */
    {
        .node_index = 29,
        .parent_index = 27,
        .depth = 2,
        .link_start = 3,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 2,
        .init_function_index = 5,
        .aux_function_index = 0,
        .term_function_index = 0,
        .node_data_id = 65535
    },
    /* [30] _2 */
    {
        .node_index = 30,
        .parent_index = 27,
        .depth = 2,
        .link_start = 3,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 4,
        .init_function_index = 0,
        .aux_function_index = 0,
        .term_function_index = 0,
        .node_data_id = 65535
    },
    /* [31] kb1 */
    {
        .node_index = 31,
        .parent_index = 65535,
        .depth = 0,
        .link_start = 15,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 0,
        .init_function_index = 0,
        .aux_function_index = 0,
        .term_function_index = 0,
        .node_data_id = 65535
    },
    /* [32] FILTERED */ {
        .node_index = 32, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [33] FILTERED */ {
        .node_index = 33, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [34] FILTERED */ {
        .node_index = 34, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [35] FILTERED */ {
        .node_index = 35, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [36] FILTERED */ {
        .node_index = 36, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [37] kbapp */
    {
        .node_index = 37,
        .parent_index = 65535,
        .depth = 0,
        .link_start = 3,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 0,
        .init_function_index = 0,
        .aux_function_index = 0,
        .term_function_index = 0,
        .node_data_id = 65535
    },
    /* [38] FILTERED */ {
        .node_index = 38, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [39] FILTERED */ {
        .node_index = 39, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [40] FILTERED */ {
        .node_index = 40, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [41] FILTERED */ {
        .node_index = 41, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [42] FILTERED */ {
        .node_index = 42, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [43] kb0 */
    {
        .node_index = 43,
        .parent_index = 65535,
        .depth = 0,
        .link_start = 11,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 0,
        .init_function_index = 0,
        .aux_function_index = 0,
        .term_function_index = 0,
        .node_data_id = 65535
    },
    /* [44] FILTERED */ {
        .node_index = 44, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [45] FILTERED */ {
        .node_index = 45, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [46] FILTERED */ {
        .node_index = 46, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [47] FILTERED */ {
        .node_index = 47, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [48] FILTERED */ {
        .node_index = 48, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [49] FILTERED */ {
        .node_index = 49, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [50] FILTERED */ {
        .node_index = 50, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [51] FILTERED */ {
        .node_index = 51, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [52] FILTERED */ {
        .node_index = 52, .parent_index = 0xFFFF, .depth = 0,
        .link_start = 0, .link_count = 0,
        .main_function_index = 0, .init_function_index = 0,
        .aux_function_index = 0, .term_function_index = 0,
        .node_data_id = 0xFFFF
    },
    /* [53] event_string_table */
    {
        .node_index = 53,
        .parent_index = 65535,
        .depth = 0,
        .link_start = 3,
        .link_count = 0x0000,  /* count=0, auto_start=false */
        .main_function_index = 0,
        .init_function_index = 0,
        .aux_function_index = 0,
        .term_function_index = 0,
        .node_data_id = 1
    },
};
