/* Auto-generated by ChainTree Pipeline (LuaJIT) */

#include "chaintree_handle.h"
#include "chaintree_handle_blackboard.h"

const chaintree_handle_t g_chaintree_handle = {
    .unique_id = "ct_j5te5xxi",

    .nodes = ct_j5te5xxi_nodes,
    .node_count = 35,

    .main_functions = ct_j5te5xxi_main_functions,
    .main_function_count = 6,
    .one_shot_functions = ct_j5te5xxi_one_shot_functions,
    .one_shot_function_count = 15,
    .boolean_functions = ct_j5te5xxi_boolean_functions,
    .boolean_function_count = 4,

    .main_function_names = ct_j5te5xxi_main_function_names,
    .one_shot_function_names = ct_j5te5xxi_one_shot_function_names,
    .boolean_function_names = ct_j5te5xxi_boolean_function_names,

    .main_function_usage_count = ct_j5te5xxi_main_function_usage_count,

    .link_table = ct_j5te5xxi_link_table,
    .link_table_size = 28,

    .event_strings = (const char **)ct_j5te5xxi_event_strings,
    .event_count = 27,

    .bitmask_names = (const char **)ct_j5te5xxi_bitmask_names,
    .bitmask_count = 0,

    .kb_table = ct_j5te5xxi_kb_table,
    .kb_count = 6,

    .node_data_records = ct_j5te5xxi_node_data_records,
    .node_data_records_count = 219,
    .node_data_strings = ct_j5te5xxi_node_data_strings,
    .node_data_strings_size = 662,
    .node_data_controls = ct_j5te5xxi_node_data_controls,
    .node_data_controls_count = 11,
    .bb_table = &ct_j5te5xxi_bb_table
};
