/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#ifndef CHAINTREE_HANDLE_NODES_H
#define CHAINTREE_HANDLE_NODES_H

#include "chaintree_support.h"

#define CT_K6OENYBG_NODE_COUNT 31

extern const chaintree_node_t ct_k6oenybg_nodes[CT_K6OENYBG_NODE_COUNT];

#endif /* CHAINTREE_HANDLE_NODES_H */