/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#ifndef CHAINTREE_HANDLE_LINKS_H
#define CHAINTREE_HANDLE_LINKS_H

#include <stdint.h>

#define CT_OFFKYU7F_LINK_TABLE_SIZE 28

extern const uint16_t ct_offkyu7f_link_table[CT_OFFKYU7F_LINK_TABLE_SIZE];

#endif /* CHAINTREE_HANDLE_LINKS_H */