/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#ifndef CHAINTREE_HANDLE_NODE_DATA_H
#define CHAINTREE_HANDLE_NODE_DATA_H

#include "chaintree_support.h"

extern const json_record_t ct_q83fy0hc_node_data_records[94];
extern const char ct_q83fy0hc_node_data_strings[592];
extern const record_control_t ct_q83fy0hc_node_data_controls[4];

#endif /* CHAINTREE_HANDLE_NODE_DATA_H */
