/* Auto-generated by ChainTree Pipeline (LuaJIT) - Blackboard */
#include "chaintree_handle_blackboard.h"

cfl_bb_field_t ct_j5te5xxi_bb_fields[] = {
    { .name_hash = 0, .offset = 0, .size = 4 },  /* adc0_mean */
    { .name_hash = 0, .offset = 4, .size = 4 },  /* adc0_max */
    { .name_hash = 0, .offset = 8, .size = 4 },  /* adc0_rms */
    { .name_hash = 0, .offset = 12, .size = 4 },  /* adc1_mean */
    { .name_hash = 0, .offset = 16, .size = 4 },  /* adc1_max */
    { .name_hash = 0, .offset = 20, .size = 4 },  /* adc1_rms */
    { .name_hash = 0, .offset = 24, .size = 4 },  /* adc2_mean */
    { .name_hash = 0, .offset = 28, .size = 4 },  /* adc2_max */
    { .name_hash = 0, .offset = 32, .size = 4 },  /* adc2_rms */
    { .name_hash = 0, .offset = 36, .size = 4 },  /* gpio_raw */
    { .name_hash = 0, .offset = 40, .size = 4 },  /* gpio_deb */
    { .name_hash = 0, .offset = 44, .size = 4 },  /* cnt0 */
    { .name_hash = 0, .offset = 48, .size = 4 },  /* cnt1 */
    { .name_hash = 0, .offset = 52, .size = 4 },  /* cnt2 */
    { .name_hash = 0, .offset = 56, .size = 4 },  /* cnt3 */
    { .name_hash = 0, .offset = 60, .size = 4 },  /* cnt4 */
    { .name_hash = 0, .offset = 64, .size = 4 },  /* cnt5 */
    { .name_hash = 0, .offset = 68, .size = 4 },  /* cnt6 */
    { .name_hash = 0, .offset = 72, .size = 4 },  /* cnt7 */
};

static uint8_t ct_j5te5xxi_bb_defaults[76] __attribute__((aligned(8))) = {0};

static void ct_j5te5xxi_bb_init_defaults(void) {
}

cfl_bb_record_t ct_j5te5xxi_bb_record = {
    .name_hash = 0,
    .total_size = 76,
    .field_count = 19,
    .fields = ct_j5te5xxi_bb_fields,
    .defaults = ct_j5te5xxi_bb_defaults,
};

cfl_bb_table_t ct_j5te5xxi_bb_table = {
    .blackboard = &ct_j5te5xxi_bb_record,
    .const_records = NULL,
    .const_record_count = 0,
};

void ct_j5te5xxi_bb_init_hashes(void) {
    ct_j5te5xxi_bb_fields[0].name_hash = cfl_bb_hash("adc0_mean");
    ct_j5te5xxi_bb_fields[1].name_hash = cfl_bb_hash("adc0_max");
    ct_j5te5xxi_bb_fields[2].name_hash = cfl_bb_hash("adc0_rms");
    ct_j5te5xxi_bb_fields[3].name_hash = cfl_bb_hash("adc1_mean");
    ct_j5te5xxi_bb_fields[4].name_hash = cfl_bb_hash("adc1_max");
    ct_j5te5xxi_bb_fields[5].name_hash = cfl_bb_hash("adc1_rms");
    ct_j5te5xxi_bb_fields[6].name_hash = cfl_bb_hash("adc2_mean");
    ct_j5te5xxi_bb_fields[7].name_hash = cfl_bb_hash("adc2_max");
    ct_j5te5xxi_bb_fields[8].name_hash = cfl_bb_hash("adc2_rms");
    ct_j5te5xxi_bb_fields[9].name_hash = cfl_bb_hash("gpio_raw");
    ct_j5te5xxi_bb_fields[10].name_hash = cfl_bb_hash("gpio_deb");
    ct_j5te5xxi_bb_fields[11].name_hash = cfl_bb_hash("cnt0");
    ct_j5te5xxi_bb_fields[12].name_hash = cfl_bb_hash("cnt1");
    ct_j5te5xxi_bb_fields[13].name_hash = cfl_bb_hash("cnt2");
    ct_j5te5xxi_bb_fields[14].name_hash = cfl_bb_hash("cnt3");
    ct_j5te5xxi_bb_fields[15].name_hash = cfl_bb_hash("cnt4");
    ct_j5te5xxi_bb_fields[16].name_hash = cfl_bb_hash("cnt5");
    ct_j5te5xxi_bb_fields[17].name_hash = cfl_bb_hash("cnt6");
    ct_j5te5xxi_bb_fields[18].name_hash = cfl_bb_hash("cnt7");
    ct_j5te5xxi_bb_record.name_hash = cfl_bb_hash("adc_streams");
    ct_j5te5xxi_bb_init_defaults();
}
