/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#include "chaintree_handle_functions.h"

/* Forward declarations - user must provide these functions */
extern unsigned cfl_null_main_fn(void *handle, unsigned bool_function_index, unsigned node_index, unsigned event_type, unsigned event_id, void *event_data);
extern unsigned cfl_column_main_main_fn(void *handle, unsigned bool_function_index, unsigned node_index, unsigned event_type, unsigned event_id, void *event_data);
extern unsigned cfl_disable_main_fn(void *handle, unsigned bool_function_index, unsigned node_index, unsigned event_type, unsigned event_id, void *event_data);
extern unsigned cfl_gate_node_main_main_fn(void *handle, unsigned bool_function_index, unsigned node_index, unsigned event_type, unsigned event_id, void *event_data);
extern unsigned cfl_reset_main_fn(void *handle, unsigned bool_function_index, unsigned node_index, unsigned event_type, unsigned event_id, void *event_data);
extern unsigned cfl_wait_main_fn(void *handle, unsigned bool_function_index, unsigned node_index, unsigned event_type, unsigned event_id, void *event_data);

extern void cfl_null_one_shot_fn(void *handle, unsigned node_index);
extern void adc_read_one_shot_fn(void *handle, unsigned node_index);
extern void cfl_column_init_one_shot_fn(void *handle, unsigned node_index);
extern void cfl_column_term_one_shot_fn(void *handle, unsigned node_index);
extern void cfl_gate_node_init_one_shot_fn(void *handle, unsigned node_index);
extern void cfl_gate_node_term_one_shot_fn(void *handle, unsigned node_index);
extern void cfl_wait_init_one_shot_fn(void *handle, unsigned node_index);
extern void cfl_wait_term_one_shot_fn(void *handle, unsigned node_index);
extern void mon_ping_reply_one_shot_fn(void *handle, unsigned node_index);
extern void mon_snapshot_one_shot_fn(void *handle, unsigned node_index);
extern void mon_cmd_timeout_one_shot_fn(void *handle, unsigned node_index);

extern bool cfl_null_boolean_fn(void *handle, unsigned node_index, unsigned event_type, unsigned event_id, void *event_data);
extern bool cfl_column_null_boolean_fn(void *handle, unsigned node_index, unsigned event_type, unsigned event_id, void *event_data);
extern bool cfl_gate_node_null_boolean_fn(void *handle, unsigned node_index, unsigned event_type, unsigned event_id, void *event_data);
extern bool cfl_wait_for_event_boolean_fn(void *handle, unsigned node_index, unsigned event_type, unsigned event_id, void *event_data);

const main_function_t ct_m6s5rj6o_main_functions[] = {
    cfl_null_main_fn,
    cfl_column_main_main_fn,
    cfl_disable_main_fn,
    cfl_gate_node_main_main_fn,
    cfl_reset_main_fn,
    cfl_wait_main_fn,
};

const one_shot_function_t ct_m6s5rj6o_one_shot_functions[] = {
    cfl_null_one_shot_fn,
    adc_read_one_shot_fn,
    cfl_column_init_one_shot_fn,
    cfl_column_term_one_shot_fn,
    cfl_gate_node_init_one_shot_fn,
    cfl_gate_node_term_one_shot_fn,
    cfl_wait_init_one_shot_fn,
    cfl_wait_term_one_shot_fn,
    mon_ping_reply_one_shot_fn,
    mon_snapshot_one_shot_fn,
    mon_cmd_timeout_one_shot_fn,
};

const boolean_function_t ct_m6s5rj6o_boolean_functions[] = {
    cfl_null_boolean_fn,
    cfl_column_null_boolean_fn,
    cfl_gate_node_null_boolean_fn,
    cfl_wait_for_event_boolean_fn,
};

const uint16_t ct_m6s5rj6o_main_function_usage_count[6] = {
    0,  /* CFL_NULL */
    3,  /* CFL_COLUMN_MAIN */
    3,  /* CFL_DISABLE */
    2,  /* CFL_GATE_NODE_MAIN */
    3,  /* CFL_RESET */
    3,  /* CFL_WAIT */
};

const char *ct_m6s5rj6o_main_function_names[6] = {
    "CFL_NULL",
    "CFL_COLUMN_MAIN",
    "CFL_DISABLE",
    "CFL_GATE_NODE_MAIN",
    "CFL_RESET",
    "CFL_WAIT",
};

const char *ct_m6s5rj6o_one_shot_function_names[11] = {
    "CFL_NULL",
    "ADC_READ",
    "CFL_COLUMN_INIT",
    "CFL_COLUMN_TERM",
    "CFL_GATE_NODE_INIT",
    "CFL_GATE_NODE_TERM",
    "CFL_WAIT_INIT",
    "CFL_WAIT_TERM",
    "MON_PING_REPLY",
    "MON_SNAPSHOT",
    "MON_CMD_TIMEOUT",
};

const char *ct_m6s5rj6o_boolean_function_names[4] = {
    "CFL_NULL",
    "CFL_COLUMN_NULL",
    "CFL_GATE_NODE_NULL",
    "CFL_WAIT_FOR_EVENT",
};
