/* Auto-generated by ChainTree Pipeline (LuaJIT) - Generic Support Functions */
#include "chaintree_support.h"
#include <string.h>

const char* ct_get_main_function_name(const chaintree_handle_t *handle, uint16_t func_index) {
    if (handle == NULL || handle->main_function_names == NULL) return NULL;
    if (func_index >= handle->main_function_count) return NULL;
    return handle->main_function_names[func_index];
}

int ct_get_main_function_index(const chaintree_handle_t *handle, const char *func_name) {
    if (handle == NULL || func_name == NULL || handle->main_function_names == NULL) return -1;
    for (uint16_t i = 0; i < handle->main_function_count; i++) {
        if (strcmp(func_name, handle->main_function_names[i]) == 0) return i;
    }
    return -1;
}

const char* ct_get_one_shot_function_name(const chaintree_handle_t *handle, uint16_t func_index) {
    if (handle == NULL || handle->one_shot_function_names == NULL) return NULL;
    if (func_index >= handle->one_shot_function_count) return NULL;
    return handle->one_shot_function_names[func_index];
}

int ct_get_one_shot_function_index(const chaintree_handle_t *handle, const char *func_name) {
    if (handle == NULL || func_name == NULL || handle->one_shot_function_names == NULL) return -1;
    for (uint16_t i = 0; i < handle->one_shot_function_count; i++) {
        if (strcmp(func_name, handle->one_shot_function_names[i]) == 0) return i;
    }
    return -1;
}

const char* ct_get_boolean_function_name(const chaintree_handle_t *handle, uint16_t func_index) {
    if (handle == NULL || handle->boolean_function_names == NULL) return NULL;
    if (func_index >= handle->boolean_function_count) return NULL;
    return handle->boolean_function_names[func_index];
}

int ct_get_boolean_function_index(const chaintree_handle_t *handle, const char *func_name) {
    if (handle == NULL || func_name == NULL || handle->boolean_function_names == NULL) return -1;
    for (uint16_t i = 0; i < handle->boolean_function_count; i++) {
        if (strcmp(func_name, handle->boolean_function_names[i]) == 0) return i;
    }
    return -1;
}

const char* ct_get_event_name(const chaintree_handle_t *handle, uint16_t event_index) {
    if (handle == NULL || handle->event_strings == NULL) return NULL;
    if (event_index >= handle->event_count) return NULL;
    return handle->event_strings[event_index];
}

int ct_get_event_index(const chaintree_handle_t *handle, const char *name) {
    if (handle == NULL || name == NULL || handle->event_strings == NULL) return -1;
    for (uint16_t i = 0; i < handle->event_count; i++) {
        if (strcmp(name, handle->event_strings[i]) == 0) return i;
    }
    return -1;
}

const char* ct_get_bitmask_name(const chaintree_handle_t *handle, uint8_t bit_index) {
    if (handle == NULL || handle->bitmask_names == NULL) return NULL;
    if (bit_index >= handle->bitmask_count) return NULL;
    return handle->bitmask_names[bit_index];
}

int ct_get_bitmask_index(const chaintree_handle_t *handle, const char *name) {
    if (handle == NULL || name == NULL || handle->bitmask_names == NULL) return -1;
    for (uint8_t i = 0; i < handle->bitmask_count; i++) {
        if (strcmp(name, handle->bitmask_names[i]) == 0) return i;
    }
    return -1;
}

uint16_t ct_get_kb_count(const chaintree_handle_t *handle) {
    if (handle == NULL) return 0;
    return handle->kb_count;
}
