/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#ifndef CHAINTREE_HANDLE_BITMASKS_H
#define CHAINTREE_HANDLE_BITMASKS_H

#include <stdint.h>
#include <stdbool.h>
#include <string.h>

#define CT_OEOGZSBM_BITMASK_COUNT 0

extern const char *ct_oeogzsbm_bitmask_names[1];

#endif /* CHAINTREE_HANDLE_BITMASKS_H */