/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#ifndef CHAINTREE_HANDLE_KB_INFO_H
#define CHAINTREE_HANDLE_KB_INFO_H

#include "chaintree_support.h"

#define CT_M6S5RJ6O_KB_COUNT 4


extern const chaintree_kb_info_t ct_m6s5rj6o_kb_table[4];

#endif /* CHAINTREE_HANDLE_KB_INFO_H */