-- config_tree.lua -- the LuaJIT namespace DSL (full port + extension of the Python
-- config_tree). Builds the ltree namespace into namespace_db.lua, validating each
-- device's HIL config via slave_dsl. Adds the i2c-system / boot model:
--
--   b:begin_i2c_system("bus1")                 -- one Pico bus: master + its slaves
--     b:device("cfg",   {i2c=0x50, i2c_fixed=true, boot_store=true, sub="GPIO", pins=...})
--     b:device("estop", {i2c=0x20, type="lite", sub="GPIO", pins=..., interlock=...})
--     b:device("axis",  {i2c=0x40, type="lite", sub="SERVO", pins=...})
--     b:begin_boot()                            -- walk the system's slaves ->
--     b:end_boot()                              --   sam_slaves roster (CBOR) -> extra_files on "cfg"
--   b:end_i2c_system()
--   b:commit_to(ns)
--
-- Each device node's attrs carry the full PURPOSE (type / mode / i2c / i2c_fixed /
-- boot_store + the config source), so the container's USB controller can classify
-- any chip from its UID -> node. HIL bytes are recompiled from source at commission
-- (one source of truth); extra_files are stored as generated bytes (hex).

local _dir = (debug.getinfo(1, "S").source:sub(2)):match("(.*/)") or "./"
package.path = _dir .. "?.lua;" .. package.path
local sd   = require("slave_dsl")
local cbor = require("cbor")

local ROSTER_FILE = "slvr"   -- 4-char name reserved for the SAMD21 i2c-slave roster

local function tohex(s) local t = {}; for i = 1, #s do t[i] = string.format("%02x", s:byte(i)) end; return table.concat(t) end

local Builder = {}
Builder.__index = Builder
local M = {}

function M.new(opts)
    opts = opts or {}
    return setmetatable({
        root = opts.root or "slow_bus",
        stack = {},          -- {{link,name}, ...}
        declared = {},       -- path -> {kind, attrs}
        devices = {},        -- device records (for the commissioner / roster)
        cur_system = nil,    -- current i2c_system: {path, name, slaves={}, boot_store=rec}
    }, Builder)
end

function Builder:path()
    local labels = { self.root }
    for _, s in ipairs(self.stack) do labels[#labels + 1] = s[1]; labels[#labels + 1] = s[2] end
    return table.concat(labels, ".")
end

function Builder:define_node(link, name, props)
    self.stack[#self.stack + 1] = { link, name }
    self.declared[self:path()] = { kind = link, attrs = props or {} }
    return self
end

function Builder:end_node()
    if #self.stack == 0 then error("end_node with no open node") end
    table.remove(self.stack)
    return self
end

-- device(name, opts): i2c, type, cls(=SAMD21), sub(mode), pins, interlock, rate,
-- i2c_fixed, boot_store, extra_files. Validates HIL config via slave_dsl (fail fast),
-- stores the SOURCE in attrs (recompiled at commission), records the purpose.
function Builder:device(name, opts)
    opts = opts or {}
    if not opts.sub then error("device " .. name .. ": sub (mode) required") end
    -- validate the HIL config now (slave_dsl raises on bad pins/interlock/limits)
    local u = sd.Unit(opts.i2c or 0, opts.sub)
    if opts.sub == "COUNTER" then u:counter(opts.rate or 1000) end
    if opts.sub == "SERVO" then u:servo() end
    if opts.pins then u:pins(opts.pins) end
    if opts.interlock then u:interlock(opts.interlock.name, opts.interlock.expr, opts.interlock.drive) end
    u:files()    -- compile = validate; bytes are recompiled at commission from the source

    local devpath = self:path() .. ".DEV." .. name
    local attrs = {
        cls        = opts.cls or "SAMD21",
        type       = opts.type or "lite",        -- dongle | lite | (boot_store via flag)
        i2c        = opts.i2c,
        i2c_fixed  = opts.i2c_fixed or false,
        boot_store = opts.boot_store or false,
        sub        = opts.sub,
        rate       = opts.rate,
        pins       = opts.pins or {},
        interlock  = opts.interlock,
        extra_files = opts.extra_files,          -- {name = hexstring} (manual extras)
    }
    self.declared[devpath] = { kind = "DEV", attrs = attrs }
    local rec = { path = devpath, name = name, attrs = attrs }
    self.devices[#self.devices + 1] = rec
    if self.cur_system then
        self.cur_system.slaves[#self.cur_system.slaves + 1] = rec
        if opts.boot_store then self.cur_system.boot_store = rec end
    end
    return self
end

-- ---- i2c system + boot scopes --------------------------------------------
function Builder:begin_i2c_system(name)
    self:define_node("I2C", name)
    self.cur_system = { path = self:path(), name = name, slaves = {}, boot_store = nil }
    return self
end

function Builder:end_i2c_system()
    if not self.cur_system then error("end_i2c_system with no open system") end
    self.cur_system = nil
    self:end_node()
    return self
end

function Builder:begin_boot()
    if not self.cur_system then error("begin_boot outside an i2c_system") end
    self._in_boot = true
    return self
end

-- Generate the sam_slaves roster from the system's i2c slaves and attach it as the
-- `slvr` extra-file (CBOR, hex) on the system's boot_store node. The Pico, knowing
-- the boot_store's fixed address, reads this at boot to learn its bus.
function Builder:end_boot()
    if not self._in_boot then error("end_boot without begin_boot") end
    local sys = self.cur_system
    if not sys.boot_store then error("end_boot: i2c_system " .. sys.name .. " has no boot_store device") end
    local sam = {}
    for _, d in ipairs(sys.slaves) do
        if d.attrs.i2c then
            sam[#sam + 1] = { name = d.name, type = d.attrs.type, addr = d.attrs.i2c, mode = d.attrs.sub }
        end
    end
    local blob = cbor.encode({ v = 1, sam_slaves = sam })
    local ef = sys.boot_store.attrs.extra_files or {}
    ef[ROSTER_FILE] = tohex(blob)
    sys.boot_store.attrs.extra_files = ef
    self._in_boot = false
    return self
end

-- ---- commit ---------------------------------------------------------------
function Builder:commit_to(ns, root)
    root = root or self.root
    if not self.declared[self.root] then
        self.declared[self.root] = { kind = "KB", attrs = {} }
    end
    local sub = {}
    for p, v in pairs(self.declared) do
        if p == root or p:sub(1, #root + 1) == root .. "." then sub[p] = v end
    end
    return ns:regen_subtree(root, sub)
end

return M
