-- gen_fir.lua -- design the SPU's linear-phase FIR decimation filters (windowed-
-- sinc, Hamming) and emit dsp/fir_coeffs.h. Multistage so each stage is short:
--   D1a /4  44k->11k   D1b /11 11k->1k   D2 /10 1k->100   D3 /10 100->10
-- numTaps is a multiple of the decimation factor (CMSIS arm_fir_decimate needs it).
-- DC gain normalised to 1 (decimator preserves amplitude). Run:  luajit gen_fir.lua > fir_coeffs.h
local function design(N, fs, fc)
    local h, sum, M = {}, 0.0, (N - 1) / 2
    for n = 0, N - 1 do
        local x = n - M
        local s = (x == 0) and (2*fc/fs) or (math.sin(2*math.pi*fc/fs*x) / (math.pi*x))
        local w = 0.54 - 0.46 * math.cos(2*math.pi*n / (N - 1))   -- Hamming
        h[n+1] = s * w; sum = sum + h[n+1]
    end
    for i = 1, N do h[i] = h[i] / sum end                          -- DC gain = 1
    return h
end
local function emit(name, M, h)
    io.write(string.format("// %s: /%d, %d taps\n#define %s_M %d\n#define %s_N %d\n",
        name, M, #h, name, M, name, #h))
    io.write(string.format("static const float %s_COEF[%d] = {\n", name, #h))
    for i = 1, #h do io.write(string.format("%+.9ef,%s", h[i], (i % 6 == 0) and "\n" or " ")) end
    io.write("\n};\n\n")
end
io.write("// GENERATED by dsp/gen_fir.lua -- linear-phase FIR decimation coefficients.\n")
io.write("#ifndef DSP_FIR_COEFFS_H\n#define DSP_FIR_COEFFS_H\n\n")
emit("FIR_D1A", 4,  design(64,  44000, 4500))   -- 44k -> 11k  (anti-alias < 5.5k)
emit("FIR_D1B", 11, design(88,  11000,  450))   -- 11k -> 1k   (< 500)
emit("FIR_D2",  10, design(80,   1000,   45))   -- 1k  -> 100  (< 50)
emit("FIR_D3",  10, design(80,    100,  4.5))   -- 100 -> 10   (< 5)
io.write("#endif // DSP_FIR_COEFFS_H\n")
