/*
 * cfl_blackboard.h - Shared Blackboard for ChainTree Runtime
 *
 * A single mutable blackboard shared across all knowledge bases.
 * Fields are accessed by compile-time offset (fast) or FNV-1a hash (dynamic).
 *
 * The blackboard is defined by a cfl_bb_record_t descriptor in the
 * chaintree_handle_t (ROM). At runtime, cfl_runtime_create() allocates the
 * blackboard buffer and copies defaults. All node functions access it
 * through the runtime handle.
 *
 * Constant records are read-only ROM data accessible by name hash.
 */

#ifndef CFL_BLACKBOARD_H
#define CFL_BLACKBOARD_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <string.h>

/* ========================================================================
 * FIELD DESCRIPTOR (ROM - generated by pipeline)
 * ======================================================================== */

typedef struct {
    uint32_t name_hash;     /* FNV-1a 32-bit hash of field name */
    uint16_t offset;        /* byte offset into blackboard/record */
    uint16_t size;          /* field size in bytes */
} cfl_bb_field_t;

/* ========================================================================
 * BLACKBOARD RECORD DESCRIPTOR (ROM - generated by pipeline)
 *
 * Describes the layout of the mutable blackboard.
 * ======================================================================== */

typedef struct cfl_bb_record {
    uint32_t name_hash;             /* FNV-1a of record name */
    uint16_t total_size;            /* allocation size in bytes */
    uint16_t field_count;
    const cfl_bb_field_t *fields;   /* field descriptor array */
    const void *defaults;           /* default values blob (NULL = zero-fill) */
} cfl_bb_record_t;

/* ========================================================================
 * CONSTANT RECORD (ROM - generated by pipeline)
 *
 * Read-only named data accessible by hash lookup.
 * ======================================================================== */

typedef struct {
    uint32_t name_hash;             /* FNV-1a of record name */
    uint16_t total_size;            /* byte size of data */
    uint16_t field_count;
    const cfl_bb_field_t *fields;   /* field descriptor array (optional, NULL ok) */
    const void *data;               /* pointer to const data in ROM */
} cfl_bb_const_record_t;

/* ========================================================================
 * BLACKBOARD TABLE (ROM - stored in chaintree_handle_t)
 *
 * Groups the blackboard descriptor and all constant records.
 * ======================================================================== */

typedef struct cfl_bb_table {
    const cfl_bb_record_t *blackboard;          /* mutable blackboard (NULL = none) */
    const cfl_bb_const_record_t *const_records; /* array of const records */
    uint16_t const_record_count;
} cfl_bb_table_t;

/* ========================================================================
 * FIELD ACCESS MACROS (compile-time offset, zero overhead)
 *
 * Usage:
 *   float *temp = CFL_BB_FIELD(handle, BB_TEMPERATURE_OFFSET, float);
 *   *temp = 25.0f;
 *
 *   const float *cal = CFL_BB_CONST_FIELD(data_ptr, CAL_GAIN_OFFSET, float);
 * ======================================================================== */

#define CFL_BB_FIELD(handle, offset, type) \
    ((type *)((uint8_t *)(handle)->blackboard + (offset)))

#define CFL_BB_CONST_FIELD(data_ptr, offset, type) \
    ((const type *)((const uint8_t *)(data_ptr) + (offset)))

/* ========================================================================
 * RUNTIME BLACKBOARD API
 *
 * Forward-declared: cfl_runtime_handle_t defined in cfl_engine.h
 * ======================================================================== */

struct CFL_RUNTIME_HANDLE;

/* ---- Lifecycle (called by cfl_runtime.c) ---- */

/* Allocate blackboard from perm, copy defaults. Returns false on failure. */
bool cfl_bb_init(struct CFL_RUNTIME_HANDLE *handle);

/* Reset blackboard to defaults (or zero if no defaults). */
void cfl_bb_reset(struct CFL_RUNTIME_HANDLE *handle);

/* ---- Dynamic field access (by hash) ---- */

/* Get pointer to mutable blackboard field by name hash. NULL on not found. */
void *cfl_bb_field_by_hash(struct CFL_RUNTIME_HANDLE *handle, uint32_t field_hash);

/* Get pointer to mutable blackboard field by name string. NULL on not found. */
void *cfl_bb_field_by_name(struct CFL_RUNTIME_HANDLE *handle, const char *field_name);

/* ---- Typed getters/setters (by hash) ---- */

bool  cfl_bb_set_int32(struct CFL_RUNTIME_HANDLE *handle, uint32_t field_hash, int32_t value);
int32_t cfl_bb_get_int32(struct CFL_RUNTIME_HANDLE *handle, uint32_t field_hash, int32_t default_val);

bool  cfl_bb_set_float(struct CFL_RUNTIME_HANDLE *handle, uint32_t field_hash, float value);
float cfl_bb_get_float(struct CFL_RUNTIME_HANDLE *handle, uint32_t field_hash, float default_val);

bool     cfl_bb_set_uint32(struct CFL_RUNTIME_HANDLE *handle, uint32_t field_hash, uint32_t value);
uint32_t cfl_bb_get_uint32(struct CFL_RUNTIME_HANDLE *handle, uint32_t field_hash, uint32_t default_val);

bool     cfl_bb_set_uint16(struct CFL_RUNTIME_HANDLE *handle, uint32_t field_hash, uint16_t value);
uint16_t cfl_bb_get_uint16(struct CFL_RUNTIME_HANDLE *handle, uint32_t field_hash, uint16_t default_val);

/* ---- Constant record lookup ---- */

/* Find a constant record by name hash. Returns NULL if not found. */
const cfl_bb_const_record_t *cfl_bb_const_find(
    struct CFL_RUNTIME_HANDLE *handle, uint32_t record_hash);

/* Get pointer to a field within a constant record by field hash.
 * Returns NULL if record has no field descriptors or field not found. */
const void *cfl_bb_const_field_by_hash(
    const cfl_bb_const_record_t *record, uint32_t field_hash);

/* ---- FNV-1a hash helper ---- */

static inline uint32_t cfl_bb_hash(const char *str) {
    uint32_t hash = 2166136261u;
    while (*str) {
        hash ^= (uint8_t)*str++;
        hash *= 16777619u;
    }
    return hash;
}

#ifdef __cplusplus
}
#endif

#endif /* CFL_BLACKBOARD_H */
